version: '3.1'

services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - database
        #networks:
      #   - fullstack

  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

    volumes:
      - ./storage/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 9000:8080
    links:
      - database:database
    # networks:
    #- fullstack